title: diadanl my site
email: your-email@example.com
description: this is my test site
baseurl: /
url: 'https://github.com/diadanl/diadansite'
twitter_username: ''
github_username: ''
theme: minima
plugins:
  - jekyll-feed

